# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CmrQgis
                                 A QGIS plugin
 This plugin loads collections for granules from the Common Metadata Repository
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-02-22
        copyright            : (C) 2020 by James Norton
        email                : jamesnorton@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CmrQgis class from file CmrQgis.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .cmr_qgis import CmrQgis
    return CmrQgis(iface)
